version: '3'
services:
  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: ${PGRST_DB_URI}
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: ${PGRST_DB_ANON_ROLE}
      PGRST_OPENAPI_SERVER_PROXY_URI: ${PGRST_OPENAPI_SERVER_PROXY_URI}
    depends_on:
      - db
    networks:
      - routes

  db:
    image: kartoza/postgis:13.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    volumes:
      - routes-db-data:/var/lib/postgresql
    networks:
      - routes

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      API_URL: ${API_URL}
    networks:
      - routes

volumes:
  routes-db-data:

networks:
  routes:
