version: '3'
services:
  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://routes:routes@db:5432/api
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
    depends_on:
      - db
    networks:
      - routes

  db:
    image: ryms/routes:13.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: routes
      POSTGRES_PASSWORD: routes
      POSTGRES_MULTIPLE_EXTENSIONS: postgis
    volumes:
      - routes-db-data:/var/lib/postgresql/data"
    networks:
      - routes

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      API_URL: http://localhost:3000/
    networks:
      - routes

volumes:
  routes-db-data:

networks:
  routes:
